apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
  values:
    deployment:
      replicas: 1
    certResolvers: {}
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: false
      kubernetesGateway:
        enabled: true
    gateway:
      namespacePolicy: All
    persistence:
      enabled: true
      size: 128Mi
      storageClass: k8s-cephfs
    dashboard:
      enabled: true
      ingress:
        enabled: true
        path: /dashboard/
        pathType: Prefix
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: totorolab.local
            paths:
              - /
    service:
      enabled: true
      single: true
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Local
      annotations:
        service.beta.kubernetes.io/metal-lb: "true"
        metallb.universe.tf/address-pool: public-pool
      ports:
        web:
          port: 80
          targetPort: 80
        websecure:
          port: 443
          targetPort: 443
