apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: 34.4.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
  values:
    deployment:
      replicas: 1
    service:
      enabled: true
      type: LoadBalancer
    dashboard:
      enabled: true
    certResolvers: {}
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: true
    persistence:
      enabled: true
      size: 128Mi
      storageClass: k8s-cephfs
