apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
      version: '*' # You can specify a specific version here
  interval: 1h # Reconciliation interval
  install:
    createNamespace: true
  values:
    replicaCount: 1
    image:
      repository: docker.io/jellyfin/jellyfin
      tag: ""
      pullPolicy: IfNotPresent
    serviceAccount:
      create: true
      automount: true
    deploymentStrategy:
      type: RollingUpdate
    service:
      type: ClusterIP
      port: 8096
      portName: service
    ingress:
      enabled: false
      hosts:
        - host: jellyfin.totorolab
          paths:
            - path: /
              pathType: ImplementationSpecific
    livenessProbe:
      initialDelaySeconds: 10
      tcpSocket:
        port: http
    readinessProbe:
      initialDelaySeconds: 10
      tcpSocket:
        port: http
    jellyfin:
      enableDLNA: false
      command: []
      args: []
      env: []
    persistence:
      config:
        storageClass: k8s-cephfs
        enabled: true
        accessMode: ReadWriteOnce
        size: 5Gi
      media:
        storageClass: k8s-cephfs
        enabled: true
        accessMode: ReadWriteOnce
        size: 25Gi
