replicaCount: 1
image:
  repository: docker.io/jellyfin/jellyfin
  tag: ""
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  automount: true
deploymentStrategy:
  type: RollingUpdate
service:
  type: ClusterIP
  port: 8096
  portName: service
ingress:
  enabled: false
  hosts:
    - host: jellyfin.totorolab
      paths:
        - path: /
          pathType: ImplementationSpecific
livenessProbe:
  initialDelaySeconds: 10
  tcpSocket:
    port: http
readinessProbe:
  initialDelaySeconds: 10
  tcpSocket:
    port: http
jellyfin:
  enableDLNA: false
  command: []
  args: []
  env: []
persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
  media:
    enabled: true
    accessMode: ReadWriteOnce
    size: 25Gi
