image:
  repository: ghcr.io/onedr0p/qbittorrent
  pullPolicy: IfNotPresent
settings:
  automaticPortSetup: false
env:
  TZ: UTC
service:
  main:
    ports:
      http:
        port: 8080
  bittorrent:
    enabled: false
    type: ClusterIP
    ports:
      bittorrent:
        enabled: true
        port: 6881
        protocol: TCP
        targetPort: 6881
ingress:
  main:
    enabled: false
persistence:
  config:
    enabled: false
  media:
    enabled: false
    mountPath: /media
  downloads:
    enabled: false
    mountPath: /downloads
metrics:
  enabled: false
  serviceMonitor:
    interval: 15s
    scrapeTimeout: 5s
  prometheusRule:
    enabled: false
    rules: []
exporter:
  image:
    repository: esanchezm/prometheus-qbittorrent-exporter
    tag: v1.2.0
    pullPolicy: IfNotPresent
  env:
    user: admin
    password: adminadmin
    port: 9022
    logLevel: INFO
