apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: '*'
  interval: 1h
  values:
    image:
      repository: ghcr.io/onedr0p/sonarr
      pullPolicy: IfNotPresent
    env:
      TZ: UTC
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main:
        enabled: false
    probes:
      liveness:
        enabled: false
    persistence:
      config:
        enabled: false
