apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
      version: '*'
  interval: 1h
  install:
    createNamespace: true
  values:
    replicaCount: 1
    image:
      repository: docker.io/jellyfin/jellyfin
      tag: ""
      pullPolicy: IfNotPresent
    serviceAccount:
      create: true
      automount: true
    deploymentStrategy:
      type: RollingUpdate
    service:
      enabled: true
      single: true
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Local
      annotations:
        service.beta.kubernetes.io/metal-lb: "true"
        metallb.universe.tf/address-pool: public-pool
      port: 8096
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      hosts:
        - host: jellyfin.totorolab.local
          paths:
            - path: /
              pathType: Prefix
    livenessProbe:
      initialDelaySeconds: 10
      tcpSocket:
        port: http
    readinessProbe:
      initialDelaySeconds: 10
      tcpSocket:
        port: http
    jellyfin:
      enableDLNA: false
      command: []
      args: []
      env: []
    persistence:
      config:
        storageClass: k8s-cephfs
        enabled: true
        accessMode: ReadWriteOnce
        size: 5Gi
      media:
        storageClass: k8s-cephfs
        enabled: true
        accessMode: ReadWriteOnce
        size: 25Gi
